# Jekyll Config File

title: Op z'n Hagevelds
markdown: kramdown
permalink: /:title
paginate_path: "/pagina/:num/"
theme: minima
safe: true
paginate: 4
timezone: Europe/Amsterdam
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
